[package]
name = "engine-script"
version.workspace = true
edition.workspace = true

[dependencies]
engine-core = { path = "../engine-core" }
engine-physics = { path = "../engine-physics" }
engine-scene = { path = "../engine-scene" }
hecs.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
mlua.workspace = true
rand.workspace = true

[dev-dependencies]
glam.workspace = true
